# Generated by Django 4.1.7 on 2023-07-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_delete_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('zipcode', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Kod')),
                ('division', models.CharField(max_length=50, verbose_name='Dział')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
    ]
