# Generated by Django 4.1.7 on 2023-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_delete_userprofileform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
